general {
    lock_cmd = /home/ian/dotfiles/hypr/scripts/lock_action.sh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
}

# Listener for battery: lock screen after 5 minutes (300 seconds)
listener {
    timeout = 300
    on-timeout = /home/ian/dotfiles/hypr/scripts/lock_check.sh 300
    on-resume = hyprctl dispatch dpms on
}

# Listener for AC: lock screen after 10 minutes (600 seconds)
listener {
    timeout = 600
    on-timeout = /home/ian/dotfiles/hypr/scripts/lock_check.sh 600
    on-resume = hyprctl dispatch dpms on
}