general {
    hide_cursor = true
    grace = 0
}

background {
    monitor = 
    path = /home/ian/dotfiles/wallpapers/horses.png
    blur_passes = 0
    blur_size = 0
}

#clock

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_family = Jetbrains Mono Nerd Font Bold
    font_size = 112
    color = rgba(54, 36, 36, 1.0)
    position = 60, 50
    halign = left
    valign = center
}

#date

label {
    monitor = 
    text = cmd[update:60000] date +"%d/%m/%Y"
    font_family = Jetbrains Mono Nerd Font
    font_size = 22
    color = rgba(54, 36, 36, 1.0)
    position = 188, -42
    halign = left
    valign = center
}

#input field

input-field {
    monitor = 
    size = 225, 36
    position = 157, -140
    halign = left
    valign = center
    outline_thickness = 2

    rounding = 5
    outer_color = rgba(54, 36, 36, 1.0)
    inner_color = rgba(0, 0, 0, 0.0)
    font_color = rgba(54, 36, 36, 1.0)

    font_family = Jetbrains Mono Nerd
    placeholder_text = Digite a senha
    dots_size = 0.25
    dots_spacing = 0.4
    fade_on_empty = false
}
